<?php
$css = [
    'connexion.css'
];
?>

<div class="container">
    <form method="post" >
        <p>Bienvenue</p>
        <label for="email"></label>
        <input type="email" name="email" placeholder="Email">
        <label for="password"></label>
        <input type="password" name="password" placeholder="Mot de passe">
        <input type="submit" value="Connexion">
        <a class="link-inscription" href="/user/role">Vous n'avez pas de compte ? Rejoignez-nous maintenant !</a>
        <a href="#">Mot de passe oublié</a>
    </form>

</div>