<?php
$css = [
    'writing.css'
];
?>

<div>

    <form method="post">
        <label class="slogan" for="category-select">Catégorie:</label>
        <select name="category" id="category-select">
            <option value="" selected="selected" disabled>Choisissez une catégorie</option>
            <?php foreach ($categories as $category): ?>
                <option value="<?= htmlspecialchars($category['id'] ?? '', ENT_QUOTES, 'UTF-8'); ?>">
                    <?= htmlspecialchars($category['name'] ?? 'Nom inconnu', ENT_QUOTES, 'UTF-8'); ?>
                </option>
            <?php endforeach; ?>
        </select>
        <label class="slogan" for="title">Offrez un nom à votre création et donnez-lui le souffle de la vie.</label>
        <input class="input-title" type="text" name="title" placeholder="Votre Titre">
        <textarea class="input-textarea" name="content" placeholder="Plongez dans l'aventure de votre imagination et laissez vos mots dessiner un monde où tout devient possible."></textarea>
    </form>
    <img class="picture-one" src="/public/images/VisuelOK.png" alt="">
    <img class="picture-two" src="/public/images/plume.png" alt="">
</div>
