<?php
$css = [
    'dashboard.css'
];
?>



<div class="container">
    <h1>Espace Personnel</h1>
    <h2>Compte</h2>
    <section class="section section-management">
        <a class="link-management" href="">
            <p>Informations personnel</p>
            <i class="fa-solid fa-circle-chevron-right"></i>
        </a>
    </section>
    <h2>Abonnement</h2>
    <section class="section section-management">
        <a class="link-management" href="">
            <p>Gérer votre abonnement</p>
            <i class="fa-solid fa-circle-chevron-right"></i>
        </a>
    </section>
    <h2>Mes commentaires</h2>
    <section class="section section-management">
        <a class="link-management" href="">
            <p>Gérer vos commentaires</p>
            <i class="fa-solid fa-circle-chevron-right"></i>
        </a>
    </section>
    <h2>Ma bibliotèque</h2>
    <section class="section section-management">
        <a class="link-management" href="">
            <p>Retrouver toutes vos histoires</p>
            <i class="fa-solid fa-circle-chevron-right"></i>
        </a>
    </section>
    <section class="section section-account">
        <a class="link-account" href="">Suppression du compte</a>
        <a class="link-account" href="">Déconnexion</a>
    </section>
</div>
