<?php
$css = [
    'category.css'
];
?>

<div>
    <section class="container">
        <h1>Choisissez la catégorie qui vous fera voyager !</h1>
        <ul class="nav-list">
            <?php foreach ($categories as $category): ?>
                <li class="nav-item"><a href="#"
                                        class="nav-link"><?= htmlspecialchars($category['name'] ?? 'Nom inconnu', ENT_QUOTES, 'UTF-8'); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </section>
</div>
